apiVersion: v2
name: pagopa-platform-authorizer-config
description: Microservice that provides a set of APIs to manage authorization records for the Authorizer system.
type: application
version: 0.10.0
appVersion: 0.0.1-10-PAGOPA-1143-sviluppo-gestione-autorizzazioni-per-authorizer
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
