microservice-chart:
  namespace: "shared"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-platform-authorizer-config
    tag: "0.2.16"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.shared.internal.platform.pagopa.it"
    path: /authorizer-config/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "shared-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.30"
    limits:
      memory: "1024Mi"
      cpu: "0.7"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaplatformauthorizerconfig'
    ENV: 'prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    ENABLE_ECS_CONSOLE: "true"
    OTEL_SERVICE_NAME: "pagopa-platform-authorizer-config"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopaplatformauthorizerconfigotl,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    COSMOS_URI: "https://pagopa-p-weu-shared-auth-cosmos-account.documents.azure.com:443/"
    REDIS_PORT: "6380"
    CLIENT_READ_TIMEOUT: "10000"
    CLIENT_CONNECTION_TIMEOUT: "10000"
    APICONFIG_SELFCARE_INTEGRATION_PATH: "https://api.platform.pagopa.it/apiconfig-selfcare-integration/v1"
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    CONFIGURATION_LIMIT: "20"
    CONFIGURATION_OFFSET: "0"
    CACHE_AUTHORIZED_ENTITIES_TTL: "86400"
    SCHEDULER_ENABLED: "true"
    AUTOCACHE_SCHEDULE_CRON: "0 0 */4 * * *"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: 'elastic-otel-token-header'
    COSMOS_KEY: 'auth-p-cosmos-key'
    REDIS_PASSWORD: 'redis-password'
    REDIS_HOST: 'redis-hostname'
    APICONFIG_SELFCARE_INTEGRATION_SUBKEY: 'auth-p-apiconfig-selfcare-integration-subkey'
  keyvault:
    name: "pagopa-p-shared-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""
    create: false
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
